ljops/ljops/ljops/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from ljops.views import index,login,logout,showloading,test

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/$', index, name='index'),
    url(r'^$', index, name='index'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^showloading/$', showloading, name='showloading'),
    url(r'^ljapps/', include('ljapps.urls')),
    url(r'^workorder/', include('workorder.urls')),
    url(r'^ops/api/', include('ops.urls')),
    url(r'updatemanage/',include('updatemanage.urls')),
    url(r'^test/',test,name='test'),
]

ljops/ljops/ops/urls.py

from django.conf.urls import url
import views


urlpatterns = [
    url(r'^add_appv/', views.add_appv),
    url(r'^app_versiontype/', views.app_versiontype),
    url(r'^checkres/',  views.checkres),
    url(r'^consoleout/',  views.consoleout),
    url(r'^addappversion/',  views.addappversion),
    url(r'^deploy/',  views.deploy),
    url(r'^getdepres/',  views.getdepres),
    url(r'^done/',  views.done),
    url(r'^rollback/',  views.rollback),
    url(r'^getexelog/', views.getexelog),
    url(r'^showproject/',  views.showproject),
]

ljops/ljops/workorder/urls.py

from django.conf.urls import url
import views


urlpatterns = [
    url(r'^newapp/', views.newapp),
    url(r'^update/', views.update),
]

ljops/ljops/ljapps/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User, Group
from django.db import models
import django.utils.timezone as timezone
from django.contrib import admin
# Create your models here.

#环境  测试test  预发布pre  生产prd
class Line(models.Model):
    line_name = models.CharField(max_length=100,verbose_name='名称',unique=True)
    #line_describtion = models.CharField(max_length=100,verbose_name='描述',unique=True)
    line_level = models.IntegerField(default=0,verbose_name='等级')
    def __unicode__(self):
        return self.line_name

#机器类型,云主机，物理机，docker，kvm等
class Ostype(models.Model):
    ostype = models.CharField(max_length=100,unique=True)
    def __unicode__(self):
        return self.ostype
#机房，阿里云，腾讯云，自建机房等
class Idc(models.Model):
    idcname = models.CharField(max_length=100,unique=True)
    num = models.CharField(max_length=20,default=0)
    def __unicode__(self):
        return self.idcname

class Host(models.Model):
    idc = models.ForeignKey(Idc,blank=True)
    hostip = models.CharField(max_length=200,unique=True)
    line = models.ManyToManyField(Line,blank=True)
    ostype = models.ForeignKey(Ostype,blank=True)
    os_user = models.ManyToManyField(User,blank=True)
    os_group = models.ManyToManyField(Group,blank=True)
    lock = models.CharField(max_length=200,default=0)
    def __unicode__(self):
        return u'%s:%s'%(self.idc,self.hostip)


class Apptype(models.Model):
    typename = models.CharField(max_length=200,unique=True)
    def __unicode__(self):
        return self.typename

class Apps(models.Model):
    appname = models.CharField(max_length=200,unique=True)
    jdkversion = models.CharField(max_length=50,blank=True)
    tomcatversion = models.CharField(max_length=50,blank=True)
    urllocation = models.CharField(max_length=60,blank=True)
    prdhost = models.ManyToManyField(Host,related_name='prd_host',blank=True)
    prehost = models.ManyToManyField(Host,related_name='pre_host', blank=True)
    testhost = models.ManyToManyField(Host,related_name='test_host', blank=True)
    user = models.ManyToManyField(User,blank=True)
    appsgroup = models.ForeignKey(Group,blank=True)
    apptype = models.ForeignKey(Apptype,blank=True)
    #版本 now当前版本   rb1上个版本  rb2前个版本
    now =  models.CharField(max_length=200,blank=True)
    rb1 = models.CharField(max_length=200,blank=True)
    rb2 = models.CharField(max_length=200,blank=True)
    #生产的准备版本，刚打完的新包，更新后与now相同
    zipprd = models.CharField(max_length=200,blank=True)
    #test环境版本号
    tv = models.CharField(max_length=200,blank=True)
    # 测试的准备版本，刚打完的新包，更新后与tv相同
    ziptest = models.CharField(max_length=200, blank=True)
    #预发布环境版本号(字段废弃)
    pv = models.CharField(max_length=200,blank=True)
    #预发布环境版本 now当前版本   rb1上个版本  rb2前个版本
    prenow =  models.CharField(max_length=200,blank=True)
    prerb1 = models.CharField(max_length=200,blank=True)
    prerb2 = models.CharField(max_length=200,blank=True)
    # y预发布的准备版本，刚打完的新包,更新后与pv相同
    zippre = models.CharField(max_length=200, blank=True)
    lock = models.CharField(max_length=200,default=0)
    #newhostlock = models.CharField(max_length=200,default=0)
    #atype = models.CharField(max_length=20,blank=True)
    #0为新立项未审批的项目，1为审批通过,2为拒绝立项
    stats=models.CharField(max_length=10,default=0)
    #版本管理是git还是svn
    versionmanage = models.CharField(max_length=10, blank=True)
    #git的ssh地址，svn的ssh地址
    versionurl = models.CharField(max_length=200, blank=True)
    targetpath = models.CharField(max_length=200, blank=True)
    #appv, 立项后的tomcat包名称（独立进程无）
    appv=models.CharField(max_length=200, blank=True)
    #0没有开始升级，1为申请审批发布，1状态pre与prd不允许更新新包，审批通过后状态为2，为发布状态，发布状态不允许更新包，删除各环境的ziptest.zippre,zipprd字段,审批不通过lock为0删除各环境对应字段,
    testlock=models.CharField(max_length=10,default=0)
    prelock=models.CharField(max_length=10,default=0)
    prdlock=models.CharField(max_length=10,default=0)
    def __unicode__(self):
        return self.appname

class Funcevent(models.Model):
    app = models.ForeignKey(Apps,blank=True)
    create_time = models.DateTimeField(null=True, blank=True)
    exec_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    exeuser = models.CharField(max_length=50, blank=True)
    event_over = models.BooleanField(default=False)
    #表示事件类型，上线，回滚update   rollback
    eventtype = models.CharField(max_length=20,blank=True)
    #1 表示执行事件刚刚建立，2执行事件已经完成
    status=models.CharField(max_length=10,blank=True)
    #那个环境的上线
    destenv=models.CharField(max_length=10,blank=True)
    #要上线的包
    zip=models.CharField(max_length=200,blank=True)
    #上线结果0失败1成功
    result=models.CharField(max_length=10,blank=True)
    def __unicode__(self):
        return u'id:%s 项目名称:%s  事件类型:%s 提交时间:%s'%(self.id,self.app.appname,self.eventtype,self.create_time)
    class Meta:
        ordering = ['-id']

class Funcexe(models.Model):
    funcevent = models.ForeignKey(Funcevent,blank=True)
    host = models.ForeignKey(Host)
    exec_time = models.DateTimeField(null=True, blank=True)
    #1 notstart,2 running,3 end
    status=models.CharField(max_length=10,blank=True)
    success  = models.NullBooleanField()
    output = models.TextField(max_length=20000,blank=True)
    #要更新的目标环境test   pre  prd
    destenv=models.CharField(max_length=10,blank=True)
    #1 为回滚完成,2为回滚失败
    rollback=models.CharField(max_length=10,blank=True)
    def __unicode__(self):
        return u"时间id:%s 主机:%s 状态:%s 项目:%s"%(self.funcevent.id,self.host,self.status,self.funcevent.app.appname)

#暂未使用此表
class Action(models.Model):
    app=models.ForeignKey(Apps,blank=True)
    actionname=models.CharField(max_length=40)
    # 0
    status=models.CharField(max_length=10,default=0)
    output = models.TextField(max_length=10000, blank=True)


class Porttype(models.Model):
    porttype = models.CharField(max_length=30, unique=True)
    def __unicode__(self):
        return self.porttype

class Ports(models.Model):
    portnum = models.CharField(max_length=50)
    app = models.ForeignKey(Apps)
    porttype = models.ForeignKey(Porttype)
    comment = models.CharField(max_length=200)
    def __unicode__(self):
        return u'%s:%s' % (self.portnum, self.app.appname)


class Build_history(models.Model):
    app = models.ForeignKey(Apps, blank=True)
    filename=models.CharField(max_length=200, blank=True)
    dest=models.CharField(max_length=20, blank=True)
    branch=models.CharField(max_length=20, blank=True)
    def __unicode__(self):
        return self.filename
    class Meta:
        ordering = ['-id']

# 执行上线动作后产生历史记录
class Apps_history(models.Model):
    app = models.ForeignKey(Apps, blank=True)
    versions = models.CharField(max_length=200, blank=True)
    use_time = models.DateTimeField('上线日期', default=timezone.now)


# 负载均衡 lvs  haproxy  nginx
class Balance(models.Model):
    #lvs  haproxy  nginx
    balance_type = models.CharField(max_length=200)
    #负载均衡vip
    balance_name = models.CharField(max_length=200)
    def __unicode__(self):
        return u'%s:%s' % (self.balance_type, self.balance_name)


# 一个负载均衡服务，上面会对不同的服务做不同的监听vip配置
class Balance_attr(models.Model):
    app = models.ForeignKey(Apps, blank=True)
    balance = models.ForeignKey(Balance, blank=True)
    # 云主机的vip可以与真实ip相同
    balance_vip = models.CharField(max_length=200, blank=True)
    # port是lvs，haproxy等监听的端口(像lvs只对3层转发，不能解析域名，必须通过多端口转发不同的后端服务)
    balance_port = models.CharField(max_length=200, blank=True)
    #哪个环境的负载均衡？生产，预发？测试？（测试环境不部署负载均衡或者不需要切流量，就不配置）
    line = models.ManyToManyField(Line, blank=True)
    #（多机房，如果有2个机房，配置了2个负载均衡）
    idc = models.ForeignKey(Idc)
    def __unicode__(self):
        return u'%s:%s' % (self.app, self.balance)


# 审批表
class Approval(models.Model):
    # 需要创建approvalname=default的审批
    approvalname = models.CharField(max_length=50, blank=True)
    user = models.ManyToManyField(User, blank=True)

    def __unicode__(self):
        return u'%s' % self.user.all()





class ApprovalAdmin(admin.ModelAdmin):
    filter_horizontal = ('user',)

class AppsAdmin(admin.ModelAdmin):
    filter_horizontal = ('user','prdhost','prehost','testhost')


admin.site.register(Apps,AppsAdmin)
admin.site.register(Ostype)
admin.site.register(Idc)
admin.site.register(Host)
admin.site.register(Ports)
admin.site.register(Line)
admin.site.register(Apptype)
#Porttype 为固定值http  tomcat_shutdown  tcp
admin.site.register(Porttype)
admin.site.register(Balance)
admin.site.register(Funcevent)
admin.site.register(Funcexe)
admin.site.register(Balance_attr)
admin.site.register(Approval,ApprovalAdmin)

ljops/ljops/workorder/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

ljops/ljops/workorder/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
#from django.shortcuts import render
from django.shortcuts import render_to_response
from ljapps.models import Apps ,Ports,Porttype
from django.http import HttpResponse
from ljops.settings import fix7script,fix8script,tomcat7,tomcat8
import json,re
from django.db.models import Q
#import jenkins
from time import sleep
import threading,subprocess,signal
import logging
logger = logging.getLogger('django')

@login_required
def newapp(req):
    if req.method == 'POST':
        aid = req.POST['aid']
        action = req.POST['action']
        app=Apps.objects.get(pk=aid)
        if action=="tongguo":
            if app.apptype.typename=='dubbo' or app.apptype.typename=='daemon':
                app.stats = 1
                app.save()
                resp = {"msg": "此立项通过。"}
                return HttpResponse(json.dumps(resp), content_type="application/json")

            #1 设置jenkins，拷贝template项目到对应的jenkins新项目
            #server = jenkins.Jenkins(jkurl, username=jkusername, password=jkpassword)
            #configxml=server.get_job_config('template')
            #newconfigxml=re.sub('<url>(.*?)</url>','</url>'+app.versionurl+'</url>',configxml)
            #server.create_job(app.appname,configxml)
            # 2 生成tomcat的包
            print app.urllocation
            if app.apptype.typename == 'tomcat':
                s=True
                if app.jdkversion=="1.7":
                    cmdstr="%s %s %s %s %s %s"%(fix7script,app.appname,Ports.objects.get(app=app,porttype=Porttype.objects.get(porttype='http')).portnum,Ports.objects.get(app=app,porttype=Porttype.objects.get(porttype='tomcat_shutdown')).portnum,tomcat7,app.id)
                    cmdstr= cmdstr +" "+ '"'+app.urllocation+'"'
                    p = subprocess.Popen(cmdstr,stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True,close_fds=True)
                    while p.poll() == None:
                        sleep(1)
                    if p.poll() == 0:
                        pass
                    else:
                        s = False
                if app.jdkversion=="1.8":
                    cmd="%s %s %s %s %s %s"%(fix8script,app.appname,Ports.objects.get(app=app,porttype=Porttype.objects.get(porttype='http')).portnum,Ports.objects.get(app=app,porttype=Porttype.objects.get(porttype='tomcat_shutdown')).portnum,tomcat8,app.id)
                    print cmd
                    smdstr="%s %s %s %s %s %s"%(fix8script,app.appname,Ports.objects.get(app=app,porttype=Porttype.objects.get(porttype='http')).portnum,Ports.objects.get(app=app,porttype=Porttype.objects.get(porttype='tomcat_shutdown')).portnum,tomcat8,app.id)
                    cmdstr = cmdstr + " " + '"' + app.urllocation + '"'
                    p = subprocess.Popen(cmdstr, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,shell=True, close_fds=True)
                    while p.poll() == None:
                        sleep(1)
                    if p.poll() == 0:
                        pass
                    else:
                        s = False
                print p.stdout.read()
                try:
                    if p.stdin:
                        p.stdin.close()
                    if   p.stdout:
                        p.stdout.close()
                    if p.stderr:
                        p.stderr.close()
                except:
                    print 'ok'
                if s == False:
                    resp = {"msg": "立项脚本故障。"}
                    return HttpResponse(json.dumps(resp), content_type="application/json")
                else:
                    #app.stats=1
                    #app.save()
                    resp = {"msg": "此立项通过。"}
                    return HttpResponse(json.dumps(resp), content_type="application/json")
        else:
            app.stats=2
            app.save()
            resp={"msg": "此立项废弃。"}
            return HttpResponse(json.dumps(resp), content_type="application/json")
    else:
        #print req.user.id
        apps=Apps.objects.filter(stats='0')
        return render_to_response('workorder/newapp.html',locals())


@login_required
def update(req):
    if req.method == 'POST':
        aid = req.POST['aid']
        v = req.POST['v']
        action=req.POST['action']
        app=Apps.objects.get(pk=aid)
        print aid,v,action
        if v=='prd':
            if action=="tongguo":
                app.prdlock=2
            else:
                app.prdlock=0
                app.zipprd=''
            app.save()
        if v=="pre":
            if action=="tongguo":
                app.prelock=2
            else:
                app.prelock=0
                app.zippre=''
            app.save()
        #if action=="tongguo":
        resp = {"msg": "审批完成"}
        return HttpResponse(json.dumps(resp), content_type="application/json")
    else:
        if req.user.is_superuser == 1:
            apps = Apps.objects.filter(Q(stats='1')&(Q(prdlock='1')|Q(prelock='1')))
        else:
            apps = []
            gs = req.user.groups.all()
            for g in gs:
                aps = g.apps_set.filter(Q(stats='1')&(Q(prdlock='1')|Q(prelock='1')))
                print type(aps)
                for a in aps:
                    # print a
                    apps.append(a)
        print apps
        return render_to_response('workorder/update.html', locals())

ljops/ljops/templates/workorder/newapp.html
{% extends "index.html" %}

{% block content %}

<div class="panel panel-default">
  <div class="panel-heading">
		立项审批
  </div>
  <div class="panel-body">

      <table class="table table-bordered" id="shenpi">
          <thead>
          <tr>
              <th>项目名称</th>
              <th>项目类型</th>
              <th>项目组</th>
              <th>创建者</th>
              <th>版本管理工具</th>
              <th>jdk版本</th>
              <th>tomcat</th>
              <th>http端口</th>
              <th>shutdown端口</th>
              <th>其他端口</th>
              <th>审批</th>
          </tr>
          </thead>
          <tbody>
          {% for app in apps %}
              <tr id={{ app.id }}>
              <td>{{ app.appname }}</td>
              <td>{{ app.apptype.typename }}</td>
              <td>{{ app.appsgroup.name }}</td>
              <td>
                  {% for u in app.user.all %}
                      {{ u.username }}
                  {% endfor %}
              </td>
              <td>{{ app.versionurl }}</td>
              <td>{{ app.jdkversion }}</td>
              <td>{{ app.tomcatversion }}</td>
              <td>
                  {% for p in app.ports_set.all %}
                      {% if p.porttype.porttype == 'http' %}
                          {{ p.portnum }}
                      {% endif %}
                  {% endfor %}
              </td>

              <td>
                  {% for p in app.ports_set.all %}
                      {% if p.porttype.porttype == 'tomcat_shutdown' %}
                          {{ p.portnum }}
                      {% endif %}
                  {% endfor %}
              </td>
              <td>
                                    {% for p in app.ports_set.all %}
                      {% if p.porttype.porttype == 'tcp' %}
                          {{ p.portnum }}
                      {% endif %}
                  {% endfor %}
              </td>
              <td><a class="btn btn-default btn-success tongguo"   role="button">通过</a><a class="btn btn-default btn-warning jujue"   role="button">拒绝</a></td>
              </tr>
          {% endfor %}
          </tbody>
      </table>
  </div>

</div>



<script type="text/javascript">
$(document).ready(function() {
    $("#shenpi").on('click','.tongguo', function(event) {

       var aid=$(this).parent().parent().attr("id")
        $.post("#",{aid:aid,action:"tongguo"},function(data){
            alert(data.msg)
            window.location.reload(true)
        })
    })
})

$(document).ready(function() {
    $("#shenpi").on('click','.jujue', function(event) {

       var aid=$(this).parent().parent().attr("id")
        $.post("#",{aid:aid,action:"jujue"},function(data){
            alert(data.msg)
            window.location.reload(true)
        })
    })
})
</script>

{% endblock %}

ljops/ljops/templates/workorder/update.html
{% extends "index.html" %}
{% block content %}

<div class="panel panel-default">
  <div class="panel-heading">
		发布申请
  </div>
  <div class="panel-body">

      <table class="table table-bordered" id="fabu">
          <thead>
          <tr>
              <th>项目名称</th>
              <th>发布环境</th>
              <th>当前版本</th>
              <th>要发布的版本</th>
              <th>审批</th>
          </tr>
          </thead>
          <tbody>
          {% for app in apps %}
              {% if app.prelock == '1' %}
              <tr id="{{ app.id }}-pre">
              <td>{{ app.appname }}</td>

              <td>
                  预发布
              </td>
                  <td>
                    {{ app.prenow }}
                  </td>
                  <td>
                    {{ app.zippre }}
                  </td>
              <td><a class="btn btn-default btn-success tongguo"   role="button">审批通过</a><a class="btn btn-default btn-success jujue"   role="button">审批拒绝</a></td>

              </tr>
              {% endif %}
              {% if app.prdlock == '1' %}
               <tr id="{{ app.id }}-prd">
              <td>{{ app.appname }}</td>

              <td>
                  生产环境
              </td>
                  <td>
                    {{ app.now }}
                  </td>
                  <td>

                    {{ app.zipprd }}
                  </td>
              <td><a class="btn btn-default btn-success tongguo"   role="button">审批通过</a><a class="btn btn-default btn-warning jujue"   role="button">审批拒绝</a></td>

              </tr>
              {% endif %}
          {% endfor %}
          </tbody>
      </table>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
    $("#fabu").on('click','.tongguo', function(event) {
       var idandv=$(this).parent().parent().attr("id")
       var aid=idandv.split('-')[0]
        var v=idandv.split('-')[1]
            $.post("#",{aid:aid,v:v,action:"tongguo"},function(data){
            alert(data.msg)
            window.location.reload(true)
        })
    })
})

    $(document).ready(function() {
    $("#fabu").on('click','.jujue', function(event) {
       var idandv=$(this).parent().parent().attr("id")
       var aid=idandv.split('-')[0]
        var v=idandv.split('-')[1]
            $.post("#",{aid:aid,v:v,action:"jujue"},function(data){
            alert(data.msg)
            window.location.reload(true)
        })
    })
})
</script>

{% endblock %}